force-app/main/default/objects/Batch_Size_Setting__mdt/Batch_Size_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom meta data use to store different batch size. So in future if batch is failing because of limit we don&apos;t have to commit through pipeline.</description>
    <label>Batch Size Setting</label>
    <pluralLabel>Batch Size Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Size_Setting__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Define the batch size</description>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Trip__c/Field_Trip__c.object-meta.xml
<CustomObject>
    <description>Use to store the field use</description>
    <label>Field Trip</label>
    <nameField>
        <displayFormat>FT- {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Trip__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Store the field name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Trip__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Trip__c/fields/FieldTripName__c.field-meta.xml
<CustomField>
    <fullName>FieldTripName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Trip Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Trip__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>To store the object Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Trip__c/fields/Uses__c.field-meta.xml
<CustomField>
    <fullName>Uses__c</fullName>
    <description>To store the use percentage</description>
    <label>Uses</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FieldTripUtility.cls
/**
 * Utility class for Field Tripping
 */
public without sharing class FieldTripUtility {
    
    @AuraEnabled
    public static List<SelectionOption> getFieldTripNames() {
        List<SelectionOption> fieldTripNames = new List<SelectionOption>();

        SelectionOption option = new SelectionOption();
        option.label = '--- None ---';
        option.value = '';
        fieldTripNames.add(option);

        for (AggregateResult aggResult : [SELECT FieldTripName__c FROM Field_Trip__c GROUP BY FieldTripName__c]) {
            SelectionOption r = new SelectionOption();
            r.label = (String)aggResult.get('FieldTripName__c');
            r.value = (String)aggResult.get('FieldTripName__c');

            fieldTripNames.add(r);
        }

        return fieldTripNames;
    }


    @AuraEnabled(cacheable=true)
    public static List<Field_Trip__c> getFieldTripRecordByName(String fieldTripName) {
        return [
            SELECT
                Object__c,
                Field__c,
                Field_Type__c,
                Uses__c
            FROM Field_Trip__c
            WHERE FieldTripName__c =: fieldTripName
            ORDER BY Uses__c DESC
        ];
    }


    @AuraEnabled
    public static Boolean deleteFieldTripRecordByName(String fieldTripName) {
        List<Field_Trip__c> ftList = [
            SELECT
                Object__c,
                Field__c,
                Field_Type__c,
                Uses__c
            FROM Field_Trip__c
            WHERE FieldTripName__c =: fieldTripName
        ];

        delete ftList;

        return true;
    }


    public class FieldTripRequest {

        @InvocableVariable
        public String fieldTripName;

        @InvocableVariable
        public String objectName;

        @InvocableVariable
        public String whereClause;

        @InvocableVariable
        public String submitterEmail;
    }

    public class FieldTripResult {

        @InvocableVariable
        public Boolean isDuplicate;
    }


    @InvocableMethod (label='Calculate Field Trip')
    public static List<FieldTripResult> calculateFieldTrip(List<FieldTripRequest> request) {

        String fieldTripName = request.get(0).fieldTripName;
        String objectName = request.get(0).objectName;
        String whereClause = request.get(0).whereClause;
        String submitterEmail = request.get(0).submitterEmail;

        List<FieldTripResult> results = new List<FieldTripResult>();
        List<Field_Trip__c> ftList = FieldTripUtility.getFieldTripRecordByName(fieldTripName);

        if (ftList.size() > 0) {
            FieldTripResult res = new FieldTripResult();
            res.isDuplicate = true;
            results.add(res);
        }
        else {
            Integer size = (Integer)Batch_Size_Setting__mdt.getInstance('FieldTripCalculationBatch').Batch_Size__c;
            FieldTripCalculationBatch batch = new FieldTripCalculationBatch(fieldTripName, objectName, whereClause, submitterEmail);
            Database.executeBatch(batch, size); 
            
            FieldTripResult res = new FieldTripResult();
            res.isDuplicate = false;
            results.add(res);
        }

        return results;
    }


    public class SelectionOption {
        @AuraEnabled
        public String label {get;set;}

        @AuraEnabled
        public String value {get;set;}
    }
}